### ISSUE TITLE
Moving .viewing, .gravel, and .symbolism into correction grid areas

### ISSUE THREAD

**Issue by riannazandbelt** [riannazandbelt/modularity-mindfulness#1]
Hi @hellachella and @jessjodoin

I'm having an issue moving the three divs into their correction column and row areas. I've targeted them in my CSS to try designating them to their corresponding columns, but they all remained in the same spot. Any advice about how I could move them around. 

Also, by looking at the screenshots, it looks like the header section with the banner image, nav, h1 and h2 are in a two column grid. Currently, I have the entire website in a three column grid. How could I go about changing the header area to be a two column grid, while keeping the main section a three column grid? Any tips or advice would be greatly appreciated!

Thanks,
Rianna

<img width="608" alt="Screen Shot 2020-09-25 at 1 48 23 PM" src="https://user-images.githubusercontent.com/55094049/94299537-cd3e8e80-ff35-11ea-9571-f91ddd82f182.png">

**Comment by JessJodoin** [comment]
Hey!
From checking out your code a have a couple things:

Your H1 and H2 should just be an `<h1>` with an `<i>` with the Japanese characters, and a `<span>` with Rock Gardens inside
Also all Japanese characters should be in an` <i lang=“ja”>` (language set to Japanese)

How you have the grid set up is that it's on your body, so to put the viewing, gravel, and symbolism on the grid you’d have to add `display: contents` to your `<main>`

Let me know if that helps and if there's anything else I can do to help 😃

**Comment by JessJodoin** [comment]
Oh! Also, if you want to fix the nav issue you could remove the banner image from the header and place it inside your section. That way you can target the header and make it `display: flex `

like this:
```
header {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 1rem .5rem;
}
```

**Comment by riannazandbelt** [comment]
Okay, I'll try that out! And thank you so much for your help!

**Comment by JessJodoin** [comment]
Of course! That's what I'm here for 😄

**Comment by riannazandbelt** [comment]
One last quick question about using flex-end to align the _learn more_ buttons, I tried targeting 
  main a {
    align-items: flex-end;
  }

to align the buttons to the bottom of the grid, but they didn't move. Is there another way I should be targeting the buttons in order to align them?

Thanks :)

**Comment by JessJodoin** [comment]
To get the spacing for the viewing, gravel, and symbolism, make their surrounding `<div>` a flex container
```
.viewing,
.gravel,
.symbolism {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
}
```

Also the `<span>Rock Gradens</span>` should go inside the `<h1>` like this:
```
<h1>
  <i lang="ja">枯山水</i>
  <span>Rock Gardens</span>
 </h1>
```
And you should do that with your h2 in the viewing, gravel, and symbolsim

**Comment by JessJodoin** [comment]
You may also have to make the h2 a flex container as well
```
h2 {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  margin: 0 0 1.5rem;
  font-size: 1.5rem;
}
```

**Comment by riannazandbelt** [comment]
@JessJodoin

**Comment by JessJodoin** [comment]
What's up?
